### ISSUE TITLE
Initial run of multiple actions fails on HDFS

### ISSUE THREAD

**Issue by frd0** [smart-data-lake/smart-data-lake#205] opened 2020-10-28 14:36 UTC
**Describe the bug**
Submitting a feed containing two actions. When running the first time the following error appears: 

`DataObject schema is undefined. A schema must be defined if there are no existing files.`

```
Caused by: java.lang.IllegalArgumentException: requirement failed: (DataObject~source-stage) DataObject schema is undefined. A schema must be defined if there are no existing files.
	at scala.Predef$.require(Predef.scala:224)
	at io.smartdatalake.workflow.dataobject.SparkFileDataObject$class.getDataFrame(SparkFileDataObject.scala:109)
	at io.smartdatalake.workflow.dataobject.JsonFileDataObject.getDataFrame(JsonFileDataObject.scala:52)
	at io.smartdatalake.workflow.action.SparkAction$$anonfun$4.apply(SparkAction.scala:109)
	at io.smartdatalake.workflow.action.SparkAction$$anonfun$4.apply(SparkAction.scala:109)
	at scala.Option.getOrElse(Option.scala:121)
	at io.smartdatalake.workflow.action.SparkAction.enrichSubFeedDataFrame(SparkAction.scala:109)
	at io.smartdatalake.workflow.action.SparkSubFeedsAction$$anonfun$doTransform$2.apply(SparkSubFeedsAction.scala:71)
	at io.smartdatalake.workflow.action.SparkSubFeedsAction$$anonfun$doTransform$2.apply(SparkSubFeedsAction.scala:66)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at io.smartdatalake.workflow.action.SparkSubFeedsAction.doTransform(SparkSubFeedsAction.scala:66)
	at io.smartdatalake.workflow.action.SparkSubFeedsAction.init(SparkSubFeedsAction.scala:90)
	at io.smartdatalake.workflow.ActionDAGRun$$anonfun$8.apply(ActionDAGRun.scala:140)
	at io.smartdatalake.workflow.ActionDAGRun$$anonfun$8.apply(ActionDAGRun.scala:134)
	at io.smartdatalake.workflow.DAG$$anonfun$7.apply(DAG.scala:151)
	at io.smartdatalake.workflow.DAG$$anonfun$7.apply(DAG.scala:151)
	at scala.util.Try$.apply(Try.scala:192)
	at io.smartdatalake.workflow.DAG.io$smartdatalake$workflow$DAG$$computeNodeOperationResult(DAG.scala:151)
	... 26 more
```

The reason is that there is no file yet on HDFS. 
The feed fails.

When running the feeds separately they are successful. 
When running again, once the file structure is set up, they succeed as well. 

**To Reproduce**
```
action-stage {
    type = FileTransferAction
    inputId = source-sftp
    outputId = hdfs-stage
    metadata {
      feed = feed1
    }
  }

action-int {
    type = CopyAction
    inputId = hdfs-stage
    outputId = hdfs-int
    metadata {
      feed = feed1
    }
  }
```

**Expected behavior**
Independent of if it is the first or second time the feed runs, if they are run together or independently, the behaviour should be identical and succeed.

**Comment by pgruetter** [comment] 2020-10-29 08:21
@frd0 Thanks for creating this issue. Not sure if this is a bug or rather enhancement. 
Anyway, we have to check how to solve situations like this. To check the lineage in the init phase, we need to have something to work with. If the DataObject does not exist and no schema is defined, we would need to get the schema from the first feed. Should be possible somehow if breakDataFrameLineage is not set to true. @zzeekk What do you think?

**Comment by zzeekk** [comment] 2020-10-29 09:38
Hi @frd0, the problem is the first Action is a file-based action. It has no schema but just transfers raw files. The second Action is spark-based, it needs a schema. If you run this Actions in sequence, no DataFrame is passed to action-int. action-int therefore needs to get a schema from existing files, or the schema needs to be defined in config. 

I see two ways for now:
1) initialize environment by running only "action-stage"
2) define full schema in config on dataobject "hdfs-stage"

In the future we could try to give a sample file to define the schema in the config, or use minimal schema (schemaMin) in config as schema if no files or full schema are present.

What do you think about this?

**Comment by zzeekk** [comment] 2020-10-29 10:12
Or would you propose that we already transfer some files in init phase for "action-stage", if no files exist in "hdfs-stage"?

**Comment by frd0** [comment] 2020-11-04 09:56
Hi @zzeekk , thanks for the details. 
I would have expected that the framework could manage this situation (forward the file to the next action), since it does work on the subsequent run anyway. 
Anyway, I now split the actions into separate feeds and call sdl_submit twice. This solution works fine. Perhaps it should be mentioned somewhere in the doc that DF-based actions cannot directly follow file actions.

**Comment by pgruetter** [comment] 2022-02-18 14:39
I'm closing this one. This is now part of the getting started documentation and is described as first "Common problem" under troubleshooting.

**Closed by pgruetter** 2022-02-18 14:39 UTC
Labels: bug
