### ISSUE TITLE
Dry-run mode not working after upgrade

### ISSUE THREAD

**Issue by burriad** [smart-data-lake/smart-data-lake#449] opened 2022-01-12 14:51 UTC
**Describe the bug**
After upgrading to version 1.3.1 from 1.3.0, the dry-run feature stopped working. Running the bundle on the Spark cluster still works, though.

**To Reproduce**
Command line args: -u fbd_lab_efa -d SBB.CH -k <path-to-keytab> -f .* -c <path-to>\reference.conf,<path-to>\shared.conf,<path-to>\application.conf,<path-to>\corridor-conflict.conf --test dry-run

2022-01-12 15:49:32 INFO  LocalSmartDataLakeBuilder$:58 - Starting Program LocalSmartDataLakeBuilder v1.3.1
2022-01-12 15:49:35 INFO  UserGroupInformation:964 - Login successful for user fbd_lab_efa@SBB.CH using keytab file C:\devsbb\apps\kerberos\fbd_lab_efa.keytab
2022-01-12 15:49:36 INFO  LocalSmartDataLakeBuilder$:285 - Starting run: runId=1 attemptId=1 feedSel=.* appName=.* streaming=false test=Some(dry-run) givenPartitionValues=None
2022-01-12 15:49:36 INFO  ConfigLoader$:87 - Loading configuration from filesystem locations: file:///c:/devsbb/Sourcen/efa-sdp-extract-adl/src/dist/conf/reference.conf, file:///c:/devsbb/Sourcen/efa-sdp-extract-adl/src/dist/conf/shared.conf, file:///c:/devsbb/Sourcen/efa-sdp-extract-adl/src/dist/conf/application.conf, file:///c:/devsbb/Sourcen/efa-sdp-extract-adl/src/dist/conf/corridor-conflict.conf.
Exception in thread "main" com.typesafe.config.ConfigException$NotResolved: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${corridorConflict.actions})
	at com.typesafe.config.impl.ConfigReference.notResolved(ConfigReference.java:35)
	at com.typesafe.config.impl.ConfigReference.valueType(ConfigReference.java:42)
	at com.typesafe.config.impl.SimpleConfig.hasPath(SimpleConfig.java:101)
	at io.smartdatalake.config.ConfigParser$.extractConfigKeys(ConfigParser.scala:72)
	at io.smartdatalake.config.ConfigParser$.getActionsEntries(ConfigParser.scala:70)
	at io.smartdatalake.config.ConfigLoader$$anonfun$7.apply(ConfigLoader.scala:108)
	at io.smartdatalake.config.ConfigLoader$$anonfun$7.apply(ConfigLoader.scala:108)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at io.smartdatalake.config.ConfigLoader$.loadConfigFromFilesystem(ConfigLoader.scala:108)
	at io.smartdatalake.app.SmartDataLakeBuilder.startRun(SmartDataLakeBuilder.scala:291)
	at io.smartdatalake.app.SmartDataLakeBuilder.run(SmartDataLakeBuilder.scala:232)
	at io.smartdatalake.app.LocalSmartDataLakeBuilder$.main(LocalSmartDataLakeBuilder.scala:90)
	at io.smartdatalake.app.LocalSmartDataLakeBuilder.main(LocalSmartDataLakeBuilder.scala)

Process finished with exit code 1

**Expected behavior**
The dry run should complete successfully if the actual run on Spark does too.

**Additional context**
Internal SBB project, so I can't share the sources. For further questions contact Adrian Burri (adrian.burri<at>sbb.ch)

**Comment by zzeekk** [comment] 2022-01-13 19:54
Hi @burriad, looks like a problem with resolving hocon substitutions early in config parsing. I cannot reproduce it. I will contact you in Teams to see your config, if ok.

**Comment by zzeekk** [comment] 2022-02-04 14:39
Problem was using hocon substitutions/inheritance in top-level objects (dataObjects, actions), e.g.:
```
include "dataObjects1File"
include "dataObjects2File"
dataObjects ${file1.dataobjects} ${file2.dataobjects}
```
This is ok for Hocon, but as SDLB can read configuration from multiple files it checks for duplicate entries in top-level objects. This check is done before Hocon substition resolution and merging is applied, and fails if it encounters substitutions. 
Solution is to remove the substitutions and declare dataObjects directly in dataObjects1File and dataObjects2File. Hocon/SDLB will merge the dataObjects definitions of the different files automatically and check for duplicates.

**Closed as completed by zzeekk** 2022-02-04 14:39 UTC
Labels: bug
